### ISSUE TITLE
things to add to resume

### ISSUE THREAD

**Issue by chrispmak** [xiaoerge/resume#2]
- sourcecontrol: employers are looking for those with github experience. add all the things you've used (bitbucket, subversion, etc)

- they're also looking for those with agile experience, scrum/kanban, whatever. 

- specify the first OP listing is for intership (java) and add any other interships experiences 

- highlight notable work accomplishments. like the time u took initiative to create the build dashboard with angularjs or OP mobile prototype

- add tools used for day to day activities (ie. jenkins for continuous integration, jira for issues management)

- add contact info

**Comment by xiaoerge** [comment]
New resume.json file is added to repo

**Comment by chrispmak** [comment]
Oh and office practicum is the product.  U work at connexin.

**Comment by xiaoerge** [comment]
OP is what we refer to ourselves on LinkedIn.

**Comment by chrispmak** [comment]
lol, i see some listed themselves as "working at office practicum" and others "working at connexin software"
